version: "3.9"
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - simple_travel_simple_travel

networks:
  simple_travel_simple_travel:
    external: true
